### ISSUE TITLE
six four

### ISSUE THREAD

**Issue by janIpen** [bandlab/eslint-config-bandlab#27]
I have no idea which repo this goes in, but I know you'll still see it.
6/4 time signatures are broken when it comes to drum kit. I think it is the same for any number of beats per bar other than 4, but i have not tested it yet. please fix the drum kit, I don't know what else to use.

**Comment by janIpen** [comment]
also alternate time signatures in general dont work properly

**Comment by pioug** [comment]
Thank you for your report. I have shared it with the team.

In the future, please use the correct reporting channel. The developers responsible for maintaining the ESLint configuration may not be involved in every aspect of BandLab.

You can submit a report directly within the app or reach out to the BandLab community on platforms such as Reddit or Discord. The links for these resources are https://www.reddit.com/r/Bandlab/ and https://discord.com/invite/bandlab.
